install: true
before_script:
  - gem install bundler -v "~> 1.17"
  - bundle install
  - bundle exec xcake make
  - bundle exec pod install --verbose

script:
  - xcodebuild -workspace ECDSATest.xcworkspace -scheme ECDSATest -sdk iphonesimulator

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode11.5